package com.comphenix.protocol.wrappers;

public class WrappedTeamParameters extends AbstractWrapper {
    private WrappedChatComponent displayName=WrappedChatComponent.fromText(""); private WrappedChatComponent prefix=WrappedChatComponent.fromText(""); private WrappedChatComponent suffix=WrappedChatComponent.fromText(""); private EnumWrappers.TeamVisibility visibility=EnumWrappers.TeamVisibility.ALWAYS; private EnumWrappers.TeamCollisionRule collision=EnumWrappers.TeamCollisionRule.ALWAYS; private EnumWrappers.ChatFormatting color=EnumWrappers.ChatFormatting.RESET; private int options;
    public WrappedTeamParameters(Object handle){super(handle==null?Object.class:handle.getClass());if(handle!=null)setHandle(handle);}
    private WrappedTeamParameters(Builder b){super(WrappedTeamParameters.class);displayName=b.displayName;prefix=b.prefix;suffix=b.suffix;visibility=b.visibility;collision=b.collision;color=b.color;options=b.options;handle=this;}
    public static Class<?> getNmsClassOrThrow(){return WrappedTeamParameters.class;} public static boolean isSupported(){return true;} public static Builder newBuilder(){return new Builder();} public static Builder newBuilder(WrappedTeamParameters value){return new Builder(value);}
    public WrappedChatComponent getDisplayName(){return displayName;} public WrappedChatComponent getPrefix(){return prefix;} public WrappedChatComponent getSuffix(){return suffix;} public EnumWrappers.TeamVisibility getNametagVisibility(){return visibility;} public EnumWrappers.TeamCollisionRule getCollisionRule(){return collision;} public EnumWrappers.ChatFormatting getColor(){return color;} public int getOptions(){return options;}
    public static class Builder { private WrappedChatComponent displayName=WrappedChatComponent.fromText("");private WrappedChatComponent prefix=WrappedChatComponent.fromText("");private WrappedChatComponent suffix=WrappedChatComponent.fromText("");private EnumWrappers.TeamVisibility visibility=EnumWrappers.TeamVisibility.ALWAYS;private EnumWrappers.TeamCollisionRule collision=EnumWrappers.TeamCollisionRule.ALWAYS;private EnumWrappers.ChatFormatting color=EnumWrappers.ChatFormatting.RESET;private int options;
        public Builder(){} public Builder(WrappedTeamParameters value){if(value!=null){displayName=value.displayName;prefix=value.prefix;suffix=value.suffix;visibility=value.visibility;collision=value.collision;color=value.color;options=value.options;}}
        public Builder displayName(WrappedChatComponent v){displayName=v;return this;} public Builder prefix(WrappedChatComponent v){prefix=v;return this;} public Builder suffix(WrappedChatComponent v){suffix=v;return this;} public Builder nametagVisibility(EnumWrappers.TeamVisibility v){visibility=v;return this;} public Builder nametagVisibility(String v){visibility=EnumWrappers.TeamVisibility.valueOf(v.toUpperCase());return this;} public Builder collisionRule(EnumWrappers.TeamCollisionRule v){collision=v;return this;} public Builder collisionRule(String v){collision=EnumWrappers.TeamCollisionRule.valueOf(v.toUpperCase());return this;} public Builder color(EnumWrappers.ChatFormatting v){color=v;return this;} public Builder options(int v){options=v;return this;} public WrappedTeamParameters build(){return new WrappedTeamParameters(this);}
    }
}
